import csv
import matplotlib.pyplot as plt
import sys

"""
Plot control signals right after simulation is stopped using a CSV file generated by the simulation.

This script reads a CSV file containing control signals and tracking errors from a robot
trajectory tracking simulation, then generates visualization plots for analysis.

Usage:
    python3 plot_signals.py <csv_filename>

Input CSV Format:
    Expected columns: timestamp, v_control_sig, w_control_sig, error, error1, error2, error3
    - timestamp: Time in seconds
    - v_control_sig: Linear velocity command (m/s)
    - w_control_sig: Angular velocity command (rad/s)
    - error: Sideway tracking error (m)
    - error1: Longitudinal error e1 (m)
    - error2: Lateral error e2 (m)
    - error3: Angular error e3 (rad)

Outputs:
    - Control signals plot (linear and angular velocity vs time)
    - Sideway tracking error plot centered around zero

Author: Ilyes Chaabeni
Date: 2025-01-05
Note: This script is intended to be run after the simulation is completed.
"""

def read_control_signals(filename):
    """
    Read control signals and tracking errors from a CSV file.
    
    This function parses a CSV file generated by the robot simulation and extracts
    all control signals and error measurements for post-processing and visualization.
    
    Args:
        filename (str): Path to the CSV file containing simulation data
        
    Returns:
        tuple: A 7-element tuple containing:
            - timestamps (list): Time values in seconds
            - v_control_sig (list): Linear velocity commands (m/s)
            - w_control_sig (list): Angular velocity commands (rad/s)
            - error (list): Sideway tracking error (m)
            - error1 (list): Longitudinal error e1 in robot frame (m)
            - error2 (list): Lateral error e2 in robot frame (m)
            - error3 (list): Angular error e3 (rad)
    
    Raises:
        FileNotFoundError: If the specified CSV file does not exist
        KeyError: If expected columns are missing from the CSV file
    """
    # Initialize empty lists to store each column of data
    timestamps = []
    v_control_sig = []
    w_control_sig = []
    error1 = []
    error2 = []
    error3 = []
    error = []
    
    # Open and read the CSV file
    with open(filename, mode='r') as file:
        reader = csv.DictReader(file)
        
        # Iterate through each row and extract values
        for row in reader:
            timestamps.append(float(row["timestamp"]))
            v_control_sig.append(float(row["v_control_sig"]))
            w_control_sig.append(float(row["w_control_sig"]))
            error.append(float(row["error"]))
            error1.append(float(row["error1"]))
            error2.append(float(row["error2"]))
            error3.append(float(row["error3"]))
    
    # Return all extracted data as a tuple
    return timestamps, v_control_sig, w_control_sig, error, error1, error2, error3

def plot_control_signals(timestamps, v_control_sig, w_control_sig, error, error1, error2, error3):
    """
    Generate visualization plots for control signals and tracking errors.
    
    This function creates two figures:
    1. Control signals (linear and angular velocity) vs time
    2. Sideway tracking error vs time with centered y-axis
    3. (Optional) Detailed error plots for e1, e2, e3 (currently commented out)
    
    Args:
        timestamps (list): Time values in seconds
        v_control_sig (list): Linear velocity commands (m/s)
        w_control_sig (list): Angular velocity commands (rad/s)
        error (list): Sideway tracking error (m)
        error1 (list): Longitudinal error e1 (m) - currently unused
        error2 (list): Lateral error e2 (m) - currently unused
        error3 (list): Angular error e3 (rad) - currently unused
    
    Returns:
        None: Displays plots using matplotlib.pyplot.show()
    """
    
    ## Figure 1: Control Signals
    plt.figure(figsize=(12, 6))

    # Subplot 1: Linear velocity command
    plt.subplot(2, 1, 1)
    plt.plot(timestamps, v_control_sig, label='Linear Velocity Command (v)')
    plt.xlabel('Timestamp')
    plt.ylabel('v (m/s)')
    plt.title('Control Signals')
    plt.legend()
    plt.grid()

    # Subplot 2: Angular velocity command
    plt.subplot(2, 1, 2)
    plt.plot(timestamps, w_control_sig, label='Angular Velocity Command (ω)', color='orange')
    plt.xlabel('Timestamp (s)')
    plt.ylabel('ω (rad/s)')
    plt.legend()
    plt.grid()
    plt.tight_layout()

    # Optional: Detailed error plots (currently commented out)
    # Uncomment the following block to visualize e1, e2, e3 separately
    # plt.figure(figsize=(12, 6))
    # plt.subplot(3, 1, 1)
    # plt.plot(timestamps, error1, label='e1', color='blue')
    # plt.xlabel('Timestamp')
    # plt.ylabel('X Error (m)')
    # plt.subplot(3, 1, 2)
    # plt.plot(timestamps, error2, label='e2', color='green')
    # plt.xlabel('Timestamp')
    # plt.ylabel('Y Error (m)')
    # plt.subplot(3, 1, 3)
    # plt.plot(timestamps, error3, label='e3', color='red')
    # plt.xlabel('Timestamp')
    # plt.ylabel('Theta Error (rad)')
    
    ## Figure 2: Sideway Tracking Error
    plt.figure(figsize=(12, 6))
    plt.title('Sideway Tracking Error')
    
    # Add horizontal reference line at y=0 for visual reference
    plt.axhline(0, color='black', linewidth=0.7)
    
    # Plot the sideway tracking error
    plt.plot(timestamps, error, label='Sideway Error', color='red')
    plt.xlabel('Timestamp (s)')
    plt.ylabel('Error (m)')
    plt.legend()
    plt.grid()

    # Center y-axis symmetrically around zero for better visualization
    # This ensures positive and negative errors are equally visible
    y_max = max(abs(min(error)), abs(max(error)))
    plt.ylim(-y_max, y_max)
    
    # Display all generated plots
    plt.show()

if __name__ == "__main__":
    """
    Main entry point for the plotting script.
    
    This block is executed when the script is run directly (not imported as a module).
    It handles command-line argument parsing, reads the CSV file, and generates plots.
    """
    
    # Validate that exactly one command-line argument (the CSV filename) is provided
    if len(sys.argv) != 2:
        print("Usage: python3 plot_signals.py <filename>")
        sys.exit(1)

    # Extract the CSV filename from command-line arguments
    filename = sys.argv[1]
    
    # Read all control signals and tracking errors from the CSV file
    # Returns: timestamps, linear velocity, angular velocity, sideway error, 
    #          longitudinal error (e1), lateral error (e2), angular error (e3)
    timestamps, v_u, w_u, e, e1, e2, e3 = read_control_signals(filename)
    
    # Generate visualization plots for all signals
    # Creates two figures: one for control signals (v, ω) and one for sideway tracking error
    plot_control_signals(timestamps, v_u, w_u, e, e1, e2, e3)